language: node_js
node_js:
  - '8'
 before_script:
 - npm install -g codeclimate-test-reporter
script:
 - npm run test
 after_script:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_TOKEN codeclimate-test-reporter < lcov.info
after_success:
 - npm run coverage
